# Generated by Django 4.1 on 2022-08-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.PositiveIntegerField()),
                ('usuario_id', models.PositiveIntegerField()),
                ('json_processo', models.TextField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessoTemporario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.PositiveIntegerField()),
                ('usuario_id', models.PositiveIntegerField()),
                ('json_processo', models.TextField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('retirado', models.BooleanField(default=False)),
                ('erro_ao_cadastrar', models.BooleanField(default=False)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
